setup-mode: true
max-players: 2
min-players: 2
game-start-countdown: 10
lobby:
  spawn:
    world: "world"
    x:
    y:
    z:
    yaw:
    pitch:
team:
  red:
    spawn:
      world: "world"
      x:
      y:
      z:
      yaw:
      pitch:
    flag:
      world: "world"
      x:
      y:
      z:
  blue:
    spawn:
      world: "world"
      x:
      y:
      z:
      yaw:
      pitch:
    flag:
      world: "world"
      x:
      y:
      z:
powerups:
  1:
    world:
    x:
    y:
    z:
