name: CaptureTheFlag
version: '${project.version}'
main: com.tqqn.capturetheflag.CaptureTheFlag
api-version: 1.16
commands:
  team:
    description: Choose a team
    usage: /<command>
    permission: team.choose
  debug:
    description: Debug Commands
    usage: /<command>
    permission: ctf.debug
  setup:
    description: Setup Commands
    usage: /<command>
    permission: ctf.setup
  kit:
    description: Kit Commands
    usage: /<command>
    permission: ctf.kit